package com.example.foryou_1.db

data class Object(
    val `data`: Data,
    val audio_id: Any?,
    val content_no: Int,
    val created_by: String,
    val created_on: String,
    val description: Any?,
    val embedded: Boolean,
    val enabled: Boolean,
    val external_id: Any?,
    val folders: Any?,
    val id: String,
    val last_modified_by: String,
    val last_modified_on: String,
    val media_alignment: String,
    val media_id: String,
    val media_position: String,
    val media_shape: String,
    val media_size: String,
    val owner_id: Any?,
    val points: Int,
    val sensitive: Boolean,
    val show_audio: Boolean,
    val show_description: Boolean,
    val show_media: Boolean,
    val show_title: Boolean,
    val stats: Stats,
    val status: String,
    val tags: List<Any>,
    val title: String,
    val title_alignment: String,
    val user_uploaded: Boolean
)